name: Flask App CI

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  flask-app-ci:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Set up Python
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: 3.10

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Lint the code
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 app.py --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 app.py --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    # Step 5: Run tests
    - name: Run tests with pytest
      run: |
        pip install pytest
        pytest

    # Step 6: Security checks (Optional but recommended)
    - name: Security check with bandit
      run: |
        pip install bandit
        bandit -r app.py

